Added check to see if version is up to date

diff --git a/.github/workflows/pypi_build_and_publish.yaml b/.github/workflows/pypi_build_and_publish.yaml
--- a/.github/workflows/pypi_build_and_publish.yaml
+++ b/.github/workflows/pypi_build_and_publish.yaml
@@ -12,12 +12,31 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout code
+      - name: Checkout repository
         uses: actions/checkout@v3
 
-      - name: Install poetry
+      - name: Install mdxcanvas
+        run: pip install mdxcanvas
+
+      - name: Extract version from toml
         run: |
-          pip install poetry
+          VERSION=$(grep -o 'version = ".*"' ${{ github.workspace }}/program/scratch/stuff.md | cut -d'"' -f2)
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
+
+      - name: Get installed mdxcanvas version
+        run: |
+          MDXCANVAS_VERSION=$(pip show mdxcanvas | grep "^Version:" | awk '{print $2}')
+          echo "MDXCANVAS_VERSION=$MDXCANVAS_VERSION" >> $GITHUB_ENV
+
+      - name: Check version mismatch
+        run: |
+          if [ "$(printf '%s\n' "$VERSION" "$MDXCANVAS_VERSION" | sort -V | head -n1)" = "$VERSION" ]; then
+            echo "Error: Please update version in .toml"
+            exit 1
+          fi
+
+      - name: Install poetry
+        run: pip install poetry
 
       - name: Build package
         run: poetry build
